export enum ACCOUNT_ASYNC_ACTION {
  GET_INFO = 'ACCOUNT_ASYNC_ACTION_GET_INFO',
  LOGIN = 'ACCOUNT_ASYNC_ACTION_LOGIN',
}
export enum ACCOUNT_ACTION {
  SET_INFO = 'ACCOUNT_ACTION_SET_INFO',
  SET_ERROR = 'ACCOUNT_ACTION_SET_ERRPR',
}
