export const SET_STATUS = 'List/SET_STATUS';

export const GET_STATUS = 'List/GET_STATUS';

export const INIT_SET_GROUPID = 'List/INIT_SET_GROUPID';

export const SET_GROUPID = 'List/SET_GROUPID';

export const GET_GROUPID = 'List/GET_GROUPID';

export const FETCH_LIST_BATCH = 'List/FETCH_LIST_BATCH';

export const FETCH_LIST = 'List/FETCH_LIST';

export const FETCH_LIST_CALLBACK = 'List/FETCH_LIST_CALLBACK';

export const SET_BATCH_REQUEST = 'List/SET_BATCH_REQUEST';

export const SET_ACTIVE_FILTER_BAR_CODE = 'List/SET_ACTIVE_FILTER_BAR_CODE';

export const UPDATE_SELECTED_FILTER = 'List/UPDATE_SELECTED_FILTER';

export const DELETE_SELECTED_FILTER = 'List/DELETE_SELECTED_FILTER';

export const CLEAR_SELECTED_FILTER = 'List/CLEAR_SELECTED_FILTER';

export const SET_LOCATIONDATEPOP_VISIBLE = 'List/SET_LOCATIONDATEPOP_VISIBLE';

export const SET_DATEPICKER_VISIBLE = 'List/SET_DATEPICKER_VISIBLE';

export const UPDATE_TEMP_SELECTED_FILTER = 'List/UPDATE_TEMP_SELECTED_FILTER';

export const RESET = 'List/RESET';
